apiVersion: v1
kind: ConfigMap
metadata:
  name: appido-config
  namespace: appido
data:
  NODE_ENV: "production"
  PORT: "8080"
  COOKIE_SECURE: "true"
  EMAIL_FROM: "APPIDO <no-reply@appido.io>"
  APPIDO_PAY_METHOD: "zarinpal"
  TELEGRAM_API_BASE: "https://api.telegram.org"
